### ISSUE TITLE
Sensors OK, Mower does not respond to commands from HASS

### ISSUE THREAD

**Issue by hubstekel** [geertmeersman/robonect#138]
Robonect for Home Assistant 1.5.4 
Husqvarna Automower 420

After installation of Robonect for Home Assistant 1.5.4  all sensors show proper info. Pressing the different commands like stop start shutdown, the mower does not respond. Via the Robonect WEBGUI everything repsonds like expected.

Did a reinstall of Robonect for Home Assistant 1.5.4, no luck.

Any tips where to look? thx

Log 

2024-03-15 09:41:00.160 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-15 09:41:00.161 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop
2024-03-15 09:41:11.625 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-15 09:41:11.625 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop
2024-03-15 09:41:11.887 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-15 09:41:11.887 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop
2024-03-15 09:41:12.203 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-15 09:41:12.203 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop
2024-03-15 09:41:12.475 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-15 09:41:12.475 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop
2024-03-15 09:41:12.777 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-15 09:41:12.777 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop

**Comment by geertmeersman** [comment]
Perhaps the MQTT Payload commands changed in this version?
Is your MQTT automower topic called "automower" in the WEBGUI?

**Comment by geertmeersman** [comment]
Hi @hubstekel , were you able to check my questions?

**Comment by hubstekel** [comment]
Hi Geert, Thx for your quick reply, at the moment I have no response with the native webgui of Robonect, when I have solved that I will try to connect again via HA.. Keep you posted. Reg, Stephan

**Comment by hubstekel** [comment]
Hi Geert, 


Connected again, some screenshots of the setup

![5](https://github.com/geertmeersman/robonect/assets/98489568/11b248f6-57ac-43af-8cd5-5fa1f6b4d03a)
![4](https://github.com/geertmeersman/robonect/assets/98489568/1b165c4f-d9a9-47f9-9c88-6efd65d11b26)
![3](https://github.com/geertmeersman/robonect/assets/98489568/d5a19e52-8ea9-4251-bdeb-99213ad2a5fa)
![2](https://github.com/geertmeersman/robonect/assets/98489568/dfb9e4c7-7b06-4b22-b7ee-a005ecf9b786)
![1](https://github.com/geertmeersman/robonect/assets/98489568/fb9af956-e336-4dbc-8d22-34dd19fe5320)

And now an error message trying to stop the mower:



024-03-16 15:00:18.327 ERROR (MainThread) [homeassistant.util.logging] Exception in async_mqtt_event_received when handling msg on 'automower/control': 'stop'
Traceback (most recent call last):
  File "/config/custom_components/robonect/sensor.py", line 59, in async_mqtt_event_received
    if slug in hass.data[DOMAIN][entry.entry_id]["sensor"]:
               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'fb4d2b4648d25ef9184ab67d2a6f7884'

2024-03-16 15:00:45.759 ERROR (MainThread) [homeassistant.util.logging] Exception in async_mqtt_event_received when handling msg on 'automower/control': 'stop'
Traceback (most recent call last):
  File "/config/custom_components/robonect/sensor.py", line 59, in async_mqtt_event_received
    if slug in hass.data[DOMAIN][entry.entry_id]["sensor"]:
               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'fb4d2b4648d25ef9184ab67d2a6f7884'

2024-03-16 15:01:54.485 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-16 15:01:54.486 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop
2024-03-16 15:01:54.523 ERROR (MainThread) [homeassistant.util.logging] Exception in async_mqtt_event_received when handling msg on 'automower/control': 'stop'
Traceback (most recent call last):
  File "/config/custom_components/robonect/sensor.py", line 59, in async_mqtt_event_received
    if slug in hass.data[DOMAIN][entry.entry_id]["sensor"]:
               ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'fb4d2b4648d25ef9184ab67d2a6f7884'

**Comment by hubstekel** [comment]
![image](https://github.com/geertmeersman/robonect/assets/98489568/363552f8-6e88-4345-90fe-84c96833e7b8)

Renamed and now no error messages but the mower does not respond:

2024-03-16 15:11:17.619 DEBUG (MainThread) [custom_components.robonect.utils] Ignoring attribute update for battery - 2600 mAh
2024-03-16 15:11:17.619 DEBUG (MainThread) [custom_components.robonect.utils] Ignoring attribute update for battery - 996 mAh
2024-03-16 15:11:20.756 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-16 15:11:20.757 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop
2024-03-16 15:13:45.262 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-16 15:13:45.262 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop
2024-03-16 15:13:46.607 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_start
2024-03-16 15:13:46.607 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: start
2024-03-16 15:13:48.284 DEBUG (MainThread) [custom_components.robonect.button] MQTT button pressed button.automower_stop
2024-03-16 15:13:48.284 DEBUG (MainThread) [custom_components.robonect.entity] [MQTT async_send_command] MQTT publish to topic: automower/control with payload: stop

**Comment by geertmeersman** [comment]
And in your robonect WEBGUI, what is the MQTT Topic you use?

**Comment by hubstekel** [comment]
hmm never seen that, now 'wel' Entered the mqtt server and tada working... Thx!

![image](https://github.com/geertmeersman/robonect/assets/98489568/53835996-df0f-4579-8d1e-07942e8b6148)

**Comment by geertmeersman** [comment]
That made sense 😀
Happy it's solved 🥳
