### ISSUE TITLE
Error adding entity binary_sensor.robonect_health_alarm for domain binary_sensor with platform robonect

### ISSUE THREAD

**Issue by lanwin** [geertmeersman/robonect#145]
**Describe the bug**
First I want to say thank you for this wonderful integration!

The integration itself works fine so far, but I noticed this error in my logs.

```
Error adding entity binary_sensor.robonect_health_alarm for domain binary_sensor with platform robonect

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 890, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1334, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 301, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/robonect/binary_sensor.py", line 199, in is_on
    self.set_is_on()
  File "/config/custom_components/robonect/binary_sensor.py", line 185, in set_is_on
    for alarm in state:
TypeError: 'NoneType' object is not iterable
```

Home Assistant version 2024.4.3

**Comment by geertmeersman** [comment]
Will check it out, thx

**Comment by geertmeersman** [comment]
Can you test with v1.6.1

**Comment by lanwin** [comment]
It seems to be gone. Thank you!
