### ISSUE TITLE
Unable to place mowing job

### ISSUE THREAD

**Issue by jstaro** [geertmeersman/robonect#180]
**Describe the bug**

I am unable to place a mowing job using the service, including via the debug service helper.
No error is bubbled up to the user; the service call is successful as far as the UI (or service call via node-red for instance) is concerned.

**Log information**

```
2024-07-08 06:03:22.555 WARNING (SyncWorker_41) [homeassistant.helpers.frame] Detected that custom integration 'robonect' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/robonect/entity.py, line 127: self.async_write_ha_state(), please report it to the author of the 'robonect' custom integration
2024-07-08 06:03:22.562 WARNING (SyncWorker_33) [homeassistant.helpers.frame] Detected that custom integration 'robonect' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/robonect/entity.py, line 127: self.async_write_ha_state(), please report it to the author of the 'robonect' custom integration
2024-07-08 06:03:22.557 ERROR (SyncWorker_41) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robonect/sensor.py", line 369, in update_busevent
    self.update_ha_state()
  File "/config/custom_components/robonect/entity.py", line 127, in update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in async_write_ha_state
    report_non_thread_safe_operation("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'robonect' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/robonect/entity.py, line 127: self.async_write_ha_state(). Please report it to the author of the 'robonect' custom integration.
2024-07-08 06:03:22.588 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/robonect/sensor.py", line 369, in update_busevent
    self.update_ha_state()
  File "/config/custom_components/robonect/entity.py", line 127, in update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in async_write_ha_state
    report_non_thread_safe_operation("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'robonect' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/robonect/entity.py, line 127: self.async_write_ha_state(). Please report it to the author of the 'robonect' custom integration.
```

**Additional context**

Version: v1.7.1
I cannot say if this used to work because this is the first version I use.
Other commands work fine, from what I can see.
I am using both MQTT and REST communication.

**Comment by geertmeersman** [comment]
Thanks, will check it out

**Comment by geertmeersman** [comment]
Hi, normally you should be able to change it through the configuration.
But if that really doesn't work, you could delete the integration config, restart HA (required), and add it again with the good rest credentials

**Comment by jstaro** [comment]
Deleting the config, then restarting HA indeed did the trick! Thanks!
Now I do see a few more entities/sensors that are reporting via REST.

The thing I missed was of course restarting HA... when will I ever learn?

Still strange that I could not change the credentials, and being forced through the REST credentials flow even if when I unchecked REST communication earlier. Perhaps adding a short explanation as to why it's a good idea to set up both protocols (either in the UI or in the README) would've prevented me from doing stupid things.

Oh, and the error swallowing I suppose. That was the big thing that tripped me up.

I'll let you decide if you want to do something about some of the abovementioned things, but I'd be totally fine if you want to close the issue since, after all, they are different problems.

**Comment by geertmeersman** [comment]
We will keep it open (as a reminder for me to check it).
It should normally update the configuration, so  have to make some tests 👍 
Thanks for reporting anyway! Always possible there is a bug somewhere!
