### ISSUE TITLE
Detected blocking call to load_verify_locations

### ISSUE THREAD

**Issue by DirkMu** [geertmeersman/robonect#208]
**Describe the bug**
I am on HA Core 2024.10 and get the following warning, which I am not sure if it was reported already: 

```
WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7fe0b26aa8d0>,) inside the event loop by custom integration 'robonect' at custom_components/robonect/__init__.py, line 81: await client.state() (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please create a bug report at https://github.com/geertmeersman/robonect/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/robonect/__init__.py", line 81, in async_setup_entry
    await client.state()
```

**To Reproduce**
Restart HA 
Maybe 2024.10 required

**Comment by geertmeersman** [comment]
According to the logs it seems an issue with the httpx library, but I'll check it out

**Comment by geertmeersman** [comment]
Should be fixed in release v2.0.0

**Comment by geertmeersman** [comment]
If all is fine, please close the issue 🙏

**Comment by DirkMu** [comment]
The warning no longer appears with version 2.0.0
