### ISSUE TITLE
Can't add integration (module 'homeassistant.components.mqtt' has no attribute 'async_wait_for_mqtt_client')

### ISSUE THREAD

**Issue by Sonderstorch** [geertmeersman/robonect#50]
**Describe the bug**
After installation with HACS and a HA restart I tried to add the integration and got a "500 internal server error".

**To Reproduce**
Just go to config/integrations and try to add the integration.

**Expected behavior**
The integration should be added.

**Screenshots**
N/A

**Log information**

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: aiohttp.server
Source: custom_components/robonect/config_flow.py:139
Integration: Robonect (documentation, issues)
First occurred: 23:29:44 (1 occurrences)
Last logged: 23:29:44

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 840, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 868, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/robonect/config_flow.py", line 540, in async_step_user
    return await self.async_step_connection_methods()
  File "/config/custom_components/robonect/config_flow.py", line 139, in async_step_connection_methods
    if not await mqtt.async_wait_for_mqtt_client(self.hass):
AttributeError: module 'homeassistant.components.mqtt' has no attribute 'async_wait_for_mqtt_client'
```

**Additional context**
Home Assistant 2023.4.6 
Frontend 20230411.1 - latest 

The MQTT component is configured in config.yaml and is using an mosquitto server on the same machine.

**Comment by geertmeersman** [comment]
Hi, is there an option that you upgrade to HA 2023.5 or higher?

**Comment by Sonderstorch** [comment]
I updated my HA instance to the current version 2023.6.1 (phew!) and was able to add the integration flawlessly. Sorry for the confusion caused and thanks for the fantastic work!

**Comment by geertmeersman** [comment]
Good news, thanks for the feedback @Sonderstorch !
