### ISSUE TITLE
Robonect not working with HA 2023.7 ?

### ISSUE THREAD

**Issue by BoneheadFraggle** [geertmeersman/robonect#56]
**Describe the bug**
After updating to HA 2023.7, all Robonect integration entities are unavailable.
I have removed the integration and added it again - no difference. "No devices or entities".

**To Reproduce**
Make sure you have a working Robonect integration in 2023.6.x, then upgrade to 2023.7.0.

**Expected behavior**
I hoped it would work as before :-)

**Screenshots**
![image](https://github.com/geertmeersman/robonect/assets/2287810/5be0b094-6d2f-4498-a03d-d7b4adb0d2be)

![image](https://github.com/geertmeersman/robonect/assets/2287810/4f1bfaae-ffa1-4c66-9f1b-a31aa7c219fa)

**Log information**
If possible activate debug logging on the component as mentioned below.

https://www.home-assistant.io/integrations/logger/

```
logger:
  default: warning
  logs:
    custom_components.nexxtmove: debug
```

**Additional context**
There are loads of errors in the log, just attaching a small part:

```
2023-07-05 21:58:39.229 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up robonect platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/robonect/binary_sensor.py", line 73, in async_setup_entry
    RobonectRestBinarySensor(
  File "/config/custom_components/robonect/binary_sensor.py", line 116, in __init__
    RobonectBinarySensor.__init__(self, hass, entry, description)
  File "/config/custom_components/robonect/binary_sensor.py", line 96, in __init__
    super().__init__(hass, entry, description)
  File "/config/custom_components/robonect/entity.py", line 54, in __init__
    else slugify(self.entity_description.name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 47, in slugify
    slug = unicode_slug.slugify(text, separator=separator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slugify/slugify.py", line 104, in slugify
    text = _unicode(text, 'utf-8', 'ignore')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decoding to str: need a bytes-like object, UndefinedType found
2023-07-05 21:58:39.234 DEBUG (MainThread) [custom_components.robonect.sensor] MQTT Subscribing to automower/#
2023-07-05 21:58:39.234 DEBUG (MainThread) [custom_components.robonect.sensor] Creating REST sensors
2023-07-05 21:58:39.234 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up robonect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/robonect/sensor.py", line 87, in async_setup_entry
    RobonectServiceSensor(
  File "/config/custom_components/robonect/sensor.py", line 358, in __init__
    super().__init__(hass, entry, description)
  File "/config/custom_components/robonect/sensor.py", line 165, in __init__
    super().__init__(hass, entry, description)
  File "/config/custom_components/robonect/entity.py", line 54, in __init__
    else slugify(self.entity_description.name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 47, in slugify
    slug = unicode_slug.slugify(text, separator=separator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/slugify/slugify.py", line 104, in slugify
    text = _unicode(text, 'utf-8', 'ignore')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: decoding to str: need a bytes-like object, UndefinedType found

```

**Comment by geertmeersman** [comment]
Hi, thanks for reporting.
What is your mqtt topic for Robonect?

Thx

**Comment by mzwanzi** [comment]
Hi,
same issue here, after updating to 2023.7 robonect not working anymore, mqtt topic in my case is 'automower'.

Thanks

**Comment by geertmeersman** [comment]
Okay, will check it this evening 👍

**Comment by gryzli133** [comment]
Same issue here, after HA update it's not working anymore

**Comment by Svanto1963** [comment]
Same issue here :(

**Comment by stuppeliene** [comment]
Same issue here...

**Comment by WouterDM** [comment]
Same issue here

**Comment by geertmeersman** [comment]
It should  be solved now, let me know if it works ;-)

**Comment by mzwanzi** [comment]
yes, after the update everything is fine again, thanks for the quick fix 👍 :)
